// Generated by tools/generate-metadata.cjs. Edit the generator and rerun it.
import '@servicenow/sdk/global'
import { Table, StringColumn, ReferenceColumn, DateTimeColumn, DateColumn, BooleanColumn, DecimalColumn, IntegerColumn, Role, Acl, ScriptInclude, BusinessRule, ApplicationMenu, Record, Form, List, default_view, UiAction, UiPage, ClientScript, RestApi, ScheduledScript, EmailNotification } from '@servicenow/sdk/core'

export const role_user = Role({ $id: Now.ID["role_user"], name: "x_1503283_vrm.user", description: "Vendor risk user" });
export const role_requester = Role({ $id: Now.ID["role_requester"], name: "x_1503283_vrm.requester", description: "Vendor risk requester", containsRoles: [role_user] });
export const role_assessor = Role({ $id: Now.ID["role_assessor"], name: "x_1503283_vrm.assessor", description: "Vendor risk assessor", containsRoles: [role_user] });
export const role_remediation_owner = Role({ $id: Now.ID["role_remediation_owner"], name: "x_1503283_vrm.remediation_owner", description: "Vendor risk remediation owner", containsRoles: [role_user] });
export const role_approver = Role({ $id: Now.ID["role_approver"], name: "x_1503283_vrm.approver", description: "Vendor risk approver", containsRoles: [role_user] });
export const role_app_admin = Role({ $id: Now.ID["role_app_admin"], name: "x_1503283_vrm.app_admin", description: "Vendor risk app admin", containsRoles: [role_user] });
export const x_1503283_vrm_vendor = Table({ name: "x_1503283_vrm_vendor", label: "Vendor", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRV",
  "number": 1000,
  "numberOfDigits": 7
},  schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
name: StringColumn({
  "label": "Vendor name",
  "maxLength": 160,
  "mandatory": true
}),
description: StringColumn({
  "label": "Description",
  "maxLength": 4000
}),
requested_by: ReferenceColumn({
  "label": "Requested by",
  "referenceTable": "sys_user"
}),
assessor: ReferenceColumn({
  "label": "Assessor",
  "referenceTable": "sys_user"
}),
approver: ReferenceColumn({
  "label": "Approver",
  "referenceTable": "sys_user"
}),
remediation_owner: ReferenceColumn({
  "label": "Remediation owner",
  "referenceTable": "sys_user"
}),
lifecycle: StringColumn({
  "label": "Lifecycle",
  "maxLength": 160,
  "choices": {
    "new": "New",
    "assessing": "Assessing",
    "remediation": "Remediation required",
    "ready_for_approval": "Ready for approval",
    "pending_approval": "Pending approval",
    "approved": "Approved",
    "rejected": "Rejected",
    "review_due": "Review due"
  },
  "dropdown": "dropdown_with_none",
  "default": "new"
}),
latest_assessment: ReferenceColumn({
  "label": "Latest assessment",
  "referenceTable": "x_1503283_vrm_assessment"
}),
risk_score: DecimalColumn({
  "label": "Risk score"
}),
risk_band: StringColumn({
  "label": "Risk band",
  "maxLength": 160,
  "choices": {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "critical": "Critical"
  },
  "dropdown": "dropdown_with_none"
}),
approved_by: ReferenceColumn({
  "label": "Approved by",
  "referenceTable": "sys_user"
}),
approved_at: DateTimeColumn({
  "label": "Approved at"
}),
next_review: DateTimeColumn({
  "label": "Next review"
}) } });

Acl({ $id: Now.ID["vendor_read"], type: 'record', table: "x_1503283_vrm_vendor", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["vendor_report"], type: 'record', table: "x_1503283_vrm_vendor", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["vendor_write"], type: 'record', table: "x_1503283_vrm_vendor", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["vendor_create"], type: 'record', table: "x_1503283_vrm_vendor", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().role('requester') || new VrmService().role('app_admin');" });

Acl({ $id: Now.ID["vendor_delete"], type: 'record', table: "x_1503283_vrm_vendor", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["vendor_number_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_name_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "name", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["vendor_description_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "description", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["vendor_requested_by_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "requested_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_assessor_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "assessor", operation: 'write', adminOverrides: false, script: "answer = new VrmService().role('app_admin');" });

Acl({ $id: Now.ID["vendor_approver_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "approver", operation: 'write', adminOverrides: false, script: "answer = new VrmService().role('app_admin');" });

Acl({ $id: Now.ID["vendor_remediation_owner_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "remediation_owner", operation: 'write', adminOverrides: false, script: "answer = new VrmService().role('app_admin');" });

Acl({ $id: Now.ID["vendor_lifecycle_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "lifecycle", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_latest_assessment_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "latest_assessment", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_risk_score_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "risk_score", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_risk_band_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "risk_band", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_approved_by_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "approved_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_approved_at_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "approved_at", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["vendor_next_review_write"], type: 'record', table: "x_1503283_vrm_vendor", field: "next_review", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["vendor_guard"], name: "VRM protect vendor", table: "x_1503283_vrm_vendor", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_vendor", view: default_view, sections: [{ caption: "Vendor", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "name"
  },
  {
    "type": "table_field",
    "field": "description"
  },
  {
    "type": "table_field",
    "field": "requested_by"
  },
  {
    "type": "table_field",
    "field": "assessor"
  },
  {
    "type": "table_field",
    "field": "approver"
  },
  {
    "type": "table_field",
    "field": "remediation_owner"
  },
  {
    "type": "table_field",
    "field": "lifecycle"
  },
  {
    "type": "table_field",
    "field": "latest_assessment"
  },
  {
    "type": "table_field",
    "field": "risk_score"
  },
  {
    "type": "table_field",
    "field": "risk_band"
  },
  {
    "type": "table_field",
    "field": "approved_by"
  },
  {
    "type": "table_field",
    "field": "approved_at"
  },
  {
    "type": "table_field",
    "field": "next_review"
  }
] }] }] });

List({ table: "x_1503283_vrm_vendor", view: default_view, columns: [
  "number",
  "name",
  "description",
  "requested_by",
  "assessor",
  "approver",
  "remediation_owner"
] });
export const related_vendor = Record({ $id: Now.ID["related_vendor"], table: 'sys_ui_related_list', data: { name: "x_1503283_vrm_vendor", view: '', sys_user: '' } });
Record({ $id: Now.ID["vendor_related_0"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_assessment.vendor", position: 0 } });
Record({ $id: Now.ID["vendor_related_1"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_finding.vendor", position: 1 } });
Record({ $id: Now.ID["vendor_related_2"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_remediation.vendor", position: 2 } });
Record({ $id: Now.ID["vendor_related_3"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_exception.vendor", position: 3 } });
Record({ $id: Now.ID["vendor_related_4"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_approval.vendor", position: 4 } });
Record({ $id: Now.ID["vendor_related_5"], table: 'sys_ui_related_list_entry', data: { list_id: related_vendor, related_list: "x_1503283_vrm_activity.vendor", position: 5 } });
export const x_1503283_vrm_questionnaire = Table({ name: "x_1503283_vrm_questionnaire", label: "Questionnaire Version", display: "name", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false,  index: [
  {
    "unique": true,
    "element": [
      "code",
      "version"
    ]
  }
], schema: { name: StringColumn({
  "label": "Name",
  "maxLength": 160,
  "mandatory": true
}),
code: StringColumn({
  "label": "Code",
  "maxLength": 160,
  "mandatory": true
}),
version: IntegerColumn({
  "label": "Version",
  "mandatory": true,
  "default": 1
}),
state: StringColumn({
  "label": "Publication state",
  "maxLength": 160,
  "choices": {
    "draft": "Draft",
    "published": "Published",
    "retired": "Retired"
  },
  "dropdown": "dropdown_with_none",
  "default": "draft"
}),
definition_json: StringColumn({
  "label": "Questionnaire definition",
  "maxLength": 65000
}) } });

Acl({ $id: Now.ID["questionnaire_read"], type: 'record', table: "x_1503283_vrm_questionnaire", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["questionnaire_report"], type: 'record', table: "x_1503283_vrm_questionnaire", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["questionnaire_write"], type: 'record', table: "x_1503283_vrm_questionnaire", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["questionnaire_create"], type: 'record', table: "x_1503283_vrm_questionnaire", operation: 'create', roles: [role_app_admin], adminOverrides: false, script: "answer = new VrmService().role('app_admin');" });

Acl({ $id: Now.ID["questionnaire_delete"], type: 'record', table: "x_1503283_vrm_questionnaire", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["questionnaire_name_write"], type: 'record', table: "x_1503283_vrm_questionnaire", field: "name", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["questionnaire_code_write"], type: 'record', table: "x_1503283_vrm_questionnaire", field: "code", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["questionnaire_version_write"], type: 'record', table: "x_1503283_vrm_questionnaire", field: "version", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["questionnaire_state_write"], type: 'record', table: "x_1503283_vrm_questionnaire", field: "state", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["questionnaire_definition_json_write"], type: 'record', table: "x_1503283_vrm_questionnaire", field: "definition_json", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

BusinessRule({ $id: Now.ID["questionnaire_guard"], name: "VRM protect questionnaire", table: "x_1503283_vrm_questionnaire", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_questionnaire", view: default_view, sections: [{ caption: "Questionnaire Version", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "name"
  },
  {
    "type": "table_field",
    "field": "code"
  },
  {
    "type": "table_field",
    "field": "version"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "definition_json"
  }
] }] }] });

List({ table: "x_1503283_vrm_questionnaire", view: default_view, columns: [
  "name",
  "code",
  "version",
  "state",
  "definition_json"
] });
export const x_1503283_vrm_assessment = Table({ name: "x_1503283_vrm_assessment", label: "Vendor Assessment", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRA",
  "number": 1000,
  "numberOfDigits": 7
},  schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
questionnaire: ReferenceColumn({
  "label": "Questionnaire version",
  "referenceTable": "x_1503283_vrm_questionnaire"
}),
snapshot_json: StringColumn({
  "label": "Immutable question snapshot",
  "maxLength": 65000
}),
request_key: StringColumn({
  "label": "Idempotency key",
  "maxLength": 160,
  "unique": true
}),
assessor: ReferenceColumn({
  "label": "Assessor",
  "referenceTable": "sys_user"
}),
state: StringColumn({
  "label": "Assessment result",
  "maxLength": 160,
  "choices": {
    "issued": "Issued",
    "passed": "Passed",
    "failed": "Failed"
  },
  "dropdown": "dropdown_with_none",
  "default": "issued"
}),
score: DecimalColumn({
  "label": "Risk score"
}),
risk_band: StringColumn({
  "label": "Risk band",
  "maxLength": 160,
  "choices": {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "critical": "Critical"
  },
  "dropdown": "dropdown_with_none"
}),
critical_failed: BooleanColumn({
  "label": "Critical control failed",
  "default": false
}),
submitted_at: DateTimeColumn({
  "label": "Submitted at"
}),
valid_until: DateTimeColumn({
  "label": "Valid until"
}) } });

Acl({ $id: Now.ID["assessment_read"], type: 'record', table: "x_1503283_vrm_assessment", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["assessment_report"], type: 'record', table: "x_1503283_vrm_assessment", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["assessment_write"], type: 'record', table: "x_1503283_vrm_assessment", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_create"], type: 'record', table: "x_1503283_vrm_assessment", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_delete"], type: 'record', table: "x_1503283_vrm_assessment", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["assessment_number_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_vendor_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_questionnaire_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "questionnaire", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_snapshot_json_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "snapshot_json", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_request_key_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "request_key", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_assessor_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "assessor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_state_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "state", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_score_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "score", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_risk_band_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "risk_band", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_critical_failed_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "critical_failed", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_submitted_at_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "submitted_at", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["assessment_valid_until_write"], type: 'record', table: "x_1503283_vrm_assessment", field: "valid_until", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["assessment_guard"], name: "VRM protect assessment", table: "x_1503283_vrm_assessment", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_assessment", view: default_view, sections: [{ caption: "Vendor Assessment", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "questionnaire"
  },
  {
    "type": "table_field",
    "field": "assessor"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "score"
  },
  {
    "type": "table_field",
    "field": "risk_band"
  },
  {
    "type": "table_field",
    "field": "critical_failed"
  },
  {
    "type": "table_field",
    "field": "submitted_at"
  },
  {
    "type": "table_field",
    "field": "valid_until"
  }
] }] }] });

List({ table: "x_1503283_vrm_assessment", view: default_view, columns: [
  "number",
  "vendor",
  "questionnaire",
  "assessor",
  "state",
  "score",
  "risk_band"
] });
export const related_assessment = Record({ $id: Now.ID["related_assessment"], table: 'sys_ui_related_list', data: { name: "x_1503283_vrm_assessment", view: '', sys_user: '' } });
Record({ $id: Now.ID["assessment_related_0"], table: 'sys_ui_related_list_entry', data: { list_id: related_assessment, related_list: "x_1503283_vrm_response.assessment", position: 0 } });
Record({ $id: Now.ID["assessment_related_1"], table: 'sys_ui_related_list_entry', data: { list_id: related_assessment, related_list: "x_1503283_vrm_finding.assessment", position: 1 } });
export const x_1503283_vrm_response = Table({ name: "x_1503283_vrm_response", label: "Assessment Response", display: "question_text", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false,  index: [
  {
    "unique": true,
    "element": [
      "assessment",
      "question_id"
    ]
  }
], schema: { assessment: ReferenceColumn({
  "label": "Assessment",
  "referenceTable": "x_1503283_vrm_assessment",
  "mandatory": true
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
question_id: StringColumn({
  "label": "Question code",
  "maxLength": 160
}),
question_text: StringColumn({
  "label": "Question",
  "maxLength": 1000
}),
options_json: StringColumn({
  "label": "Available choices",
  "maxLength": 65000
}),
answer: StringColumn({
  "label": "Answer",
  "maxLength": 160,
  "choices": {
    "yes": "Yes",
    "no": "No",
    "partial": "Partial",
    "quarterly": "Quarterly",
    "annually": "Annually",
    "never": "Never",
    "na": "Not applicable"
  },
  "dropdown": "dropdown_with_none"
}),
justification: StringColumn({
  "label": "Justification",
  "maxLength": 4000
}),
applicable: BooleanColumn({
  "label": "Applicable",
  "default": false
}),
evidence_required: BooleanColumn({
  "label": "Evidence attachment required",
  "default": false
}),
allow_na: BooleanColumn({
  "label": "N/A permitted",
  "default": false
}) } });

Acl({ $id: Now.ID["response_read"], type: 'record', table: "x_1503283_vrm_response", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["response_report"], type: 'record', table: "x_1503283_vrm_response", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["response_write"], type: 'record', table: "x_1503283_vrm_response", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["response_create"], type: 'record', table: "x_1503283_vrm_response", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_delete"], type: 'record', table: "x_1503283_vrm_response", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["response_assessment_write"], type: 'record', table: "x_1503283_vrm_response", field: "assessment", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_vendor_write"], type: 'record', table: "x_1503283_vrm_response", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_question_id_write"], type: 'record', table: "x_1503283_vrm_response", field: "question_id", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_question_text_write"], type: 'record', table: "x_1503283_vrm_response", field: "question_text", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_options_json_write"], type: 'record', table: "x_1503283_vrm_response", field: "options_json", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_answer_write"], type: 'record', table: "x_1503283_vrm_response", field: "answer", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["response_justification_write"], type: 'record', table: "x_1503283_vrm_response", field: "justification", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["response_applicable_write"], type: 'record', table: "x_1503283_vrm_response", field: "applicable", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_evidence_required_write"], type: 'record', table: "x_1503283_vrm_response", field: "evidence_required", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["response_allow_na_write"], type: 'record', table: "x_1503283_vrm_response", field: "allow_na", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["response_guard"], name: "VRM protect response", table: "x_1503283_vrm_response", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_response", view: default_view, sections: [{ caption: "Assessment Response", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "assessment"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "question_text"
  },
  {
    "type": "table_field",
    "field": "answer"
  },
  {
    "type": "table_field",
    "field": "justification"
  },
  {
    "type": "table_field",
    "field": "applicable"
  },
  {
    "type": "table_field",
    "field": "evidence_required"
  },
  {
    "type": "table_field",
    "field": "options_json"
  },
  {
    "type": "table_field",
    "field": "allow_na"
  }
] }] }] });

List({ table: "x_1503283_vrm_response", view: default_view, columns: [
  "assessment",
  "vendor",
  "question_text",
  "answer",
  "justification",
  "applicable",
  "evidence_required"
] });
export const x_1503283_vrm_finding = Table({ name: "x_1503283_vrm_finding", label: "Risk Finding", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRF",
  "number": 1000,
  "numberOfDigits": 7
}, index: [
  {
    "unique": true,
    "element": [
      "assessment",
      "question_id"
    ]
  }
], schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
assessment: ReferenceColumn({
  "label": "Assessment",
  "referenceTable": "x_1503283_vrm_assessment"
}),
question_id: StringColumn({
  "label": "Failed control",
  "maxLength": 160
}),
risk: DecimalColumn({
  "label": "Control risk"
}),
critical: BooleanColumn({
  "label": "Critical control",
  "default": false
}),
owner: ReferenceColumn({
  "label": "Owner",
  "referenceTable": "sys_user"
}),
state: StringColumn({
  "label": "Finding state",
  "maxLength": 160,
  "choices": {
    "open": "Open",
    "closed_verified": "Verified remediation"
  },
  "dropdown": "dropdown_with_none",
  "default": "open"
}),
verified_by: ReferenceColumn({
  "label": "Verified by",
  "referenceTable": "sys_user"
}),
remediation: ReferenceColumn({
  "label": "Remediation task",
  "referenceTable": "x_1503283_vrm_remediation"
}),
exception: ReferenceColumn({
  "label": "Risk exception",
  "referenceTable": "x_1503283_vrm_exception"
}),
exception_reason: StringColumn({
  "label": "Exception justification",
  "maxLength": 4000
}),
exception_until: DateTimeColumn({
  "label": "Requested exception expiry"
}) } });

Acl({ $id: Now.ID["finding_read"], type: 'record', table: "x_1503283_vrm_finding", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["finding_report"], type: 'record', table: "x_1503283_vrm_finding", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["finding_write"], type: 'record', table: "x_1503283_vrm_finding", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["finding_create"], type: 'record', table: "x_1503283_vrm_finding", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_delete"], type: 'record', table: "x_1503283_vrm_finding", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["finding_number_write"], type: 'record', table: "x_1503283_vrm_finding", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_vendor_write"], type: 'record', table: "x_1503283_vrm_finding", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_assessment_write"], type: 'record', table: "x_1503283_vrm_finding", field: "assessment", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_question_id_write"], type: 'record', table: "x_1503283_vrm_finding", field: "question_id", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_risk_write"], type: 'record', table: "x_1503283_vrm_finding", field: "risk", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_critical_write"], type: 'record', table: "x_1503283_vrm_finding", field: "critical", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_owner_write"], type: 'record', table: "x_1503283_vrm_finding", field: "owner", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_state_write"], type: 'record', table: "x_1503283_vrm_finding", field: "state", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_verified_by_write"], type: 'record', table: "x_1503283_vrm_finding", field: "verified_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_remediation_write"], type: 'record', table: "x_1503283_vrm_finding", field: "remediation", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_exception_write"], type: 'record', table: "x_1503283_vrm_finding", field: "exception", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["finding_exception_reason_write"], type: 'record', table: "x_1503283_vrm_finding", field: "exception_reason", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["finding_exception_until_write"], type: 'record', table: "x_1503283_vrm_finding", field: "exception_until", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

BusinessRule({ $id: Now.ID["finding_guard"], name: "VRM protect finding", table: "x_1503283_vrm_finding", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_finding", view: default_view, sections: [{ caption: "Risk Finding", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "assessment"
  },
  {
    "type": "table_field",
    "field": "question_id"
  },
  {
    "type": "table_field",
    "field": "risk"
  },
  {
    "type": "table_field",
    "field": "critical"
  },
  {
    "type": "table_field",
    "field": "owner"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "remediation"
  },
  {
    "type": "table_field",
    "field": "exception"
  },
  {
    "type": "table_field",
    "field": "verified_by"
  },
  {
    "type": "table_field",
    "field": "exception_reason"
  },
  {
    "type": "table_field",
    "field": "exception_until"
  }
] }] }] });

List({ table: "x_1503283_vrm_finding", view: default_view, columns: [
  "number",
  "vendor",
  "assessment",
  "question_id",
  "risk",
  "critical",
  "owner"
] });
export const related_finding = Record({ $id: Now.ID["related_finding"], table: 'sys_ui_related_list', data: { name: "x_1503283_vrm_finding", view: '', sys_user: '' } });
Record({ $id: Now.ID["finding_related_0"], table: 'sys_ui_related_list_entry', data: { list_id: related_finding, related_list: "x_1503283_vrm_remediation.finding", position: 0 } });
Record({ $id: Now.ID["finding_related_1"], table: 'sys_ui_related_list_entry', data: { list_id: related_finding, related_list: "x_1503283_vrm_exception.finding", position: 1 } });
export const x_1503283_vrm_remediation = Table({ name: "x_1503283_vrm_remediation", label: "Remediation Task", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRT",
  "number": 1000,
  "numberOfDigits": 7
},  schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
finding: ReferenceColumn({
  "label": "Finding",
  "referenceTable": "x_1503283_vrm_finding"
}),
short_description: StringColumn({
  "label": "Short description",
  "maxLength": 200
}),
assigned_to: ReferenceColumn({
  "label": "Assigned to",
  "referenceTable": "sys_user"
}),
due_date: DateTimeColumn({
  "label": "Due date"
}),
state: StringColumn({
  "label": "Task state",
  "maxLength": 160,
  "choices": {
    "open": "Open",
    "in_progress": "In progress",
    "resolved": "Awaiting verification",
    "closed_verified": "Closed and verified"
  },
  "dropdown": "dropdown_with_none",
  "default": "open"
}),
resolution: StringColumn({
  "label": "Resolution details",
  "maxLength": 4000
}),
verified_by: ReferenceColumn({
  "label": "Verified by",
  "referenceTable": "sys_user"
}),
last_reminder: DateColumn({
  "label": "Last reminder"
}) } });

Acl({ $id: Now.ID["remediation_read"], type: 'record', table: "x_1503283_vrm_remediation", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["remediation_report"], type: 'record', table: "x_1503283_vrm_remediation", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["remediation_write"], type: 'record', table: "x_1503283_vrm_remediation", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["remediation_create"], type: 'record', table: "x_1503283_vrm_remediation", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_delete"], type: 'record', table: "x_1503283_vrm_remediation", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["remediation_number_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_vendor_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_finding_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "finding", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_short_description_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "short_description", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_assigned_to_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "assigned_to", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_due_date_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "due_date", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_state_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "state", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["remediation_resolution_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "resolution", operation: 'write', adminOverrides: false, script: "answer = new VrmService().canWriteRecord(current);" });

Acl({ $id: Now.ID["remediation_verified_by_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "verified_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["remediation_last_reminder_write"], type: 'record', table: "x_1503283_vrm_remediation", field: "last_reminder", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["remediation_guard"], name: "VRM protect remediation", table: "x_1503283_vrm_remediation", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_remediation", view: default_view, sections: [{ caption: "Remediation Task", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "finding"
  },
  {
    "type": "table_field",
    "field": "short_description"
  },
  {
    "type": "table_field",
    "field": "assigned_to"
  },
  {
    "type": "table_field",
    "field": "due_date"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "resolution"
  },
  {
    "type": "table_field",
    "field": "verified_by"
  }
] }] }] });

List({ table: "x_1503283_vrm_remediation", view: default_view, columns: [
  "number",
  "vendor",
  "finding",
  "short_description",
  "assigned_to",
  "due_date",
  "state"
] });
export const x_1503283_vrm_exception = Table({ name: "x_1503283_vrm_exception", label: "Risk Exception", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRE",
  "number": 1000,
  "numberOfDigits": 7
},  schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
finding: ReferenceColumn({
  "label": "Finding",
  "referenceTable": "x_1503283_vrm_finding"
}),
requested_by: ReferenceColumn({
  "label": "Requested by",
  "referenceTable": "sys_user"
}),
approver: ReferenceColumn({
  "label": "Approver",
  "referenceTable": "sys_user"
}),
state: StringColumn({
  "label": "Exception state",
  "maxLength": 160,
  "choices": {
    "requested": "Requested",
    "approved": "Approved",
    "rejected": "Rejected",
    "expired": "Expired"
  },
  "dropdown": "dropdown_with_none",
  "default": "requested"
}),
expires_at: DateTimeColumn({
  "label": "Expires at"
}),
justification: StringColumn({
  "label": "Business justification",
  "maxLength": 4000
}),
decided_by: ReferenceColumn({
  "label": "Decided by",
  "referenceTable": "sys_user"
}) } });

Acl({ $id: Now.ID["exception_read"], type: 'record', table: "x_1503283_vrm_exception", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["exception_report"], type: 'record', table: "x_1503283_vrm_exception", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["exception_write"], type: 'record', table: "x_1503283_vrm_exception", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_create"], type: 'record', table: "x_1503283_vrm_exception", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_delete"], type: 'record', table: "x_1503283_vrm_exception", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["exception_number_write"], type: 'record', table: "x_1503283_vrm_exception", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_vendor_write"], type: 'record', table: "x_1503283_vrm_exception", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_finding_write"], type: 'record', table: "x_1503283_vrm_exception", field: "finding", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_requested_by_write"], type: 'record', table: "x_1503283_vrm_exception", field: "requested_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_approver_write"], type: 'record', table: "x_1503283_vrm_exception", field: "approver", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_state_write"], type: 'record', table: "x_1503283_vrm_exception", field: "state", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_expires_at_write"], type: 'record', table: "x_1503283_vrm_exception", field: "expires_at", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_justification_write"], type: 'record', table: "x_1503283_vrm_exception", field: "justification", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["exception_decided_by_write"], type: 'record', table: "x_1503283_vrm_exception", field: "decided_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["exception_guard"], name: "VRM protect exception", table: "x_1503283_vrm_exception", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_exception", view: default_view, sections: [{ caption: "Risk Exception", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "finding"
  },
  {
    "type": "table_field",
    "field": "requested_by"
  },
  {
    "type": "table_field",
    "field": "approver"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "expires_at"
  },
  {
    "type": "table_field",
    "field": "justification"
  },
  {
    "type": "table_field",
    "field": "decided_by"
  }
] }] }] });

List({ table: "x_1503283_vrm_exception", view: default_view, columns: [
  "number",
  "vendor",
  "finding",
  "requested_by",
  "approver",
  "state",
  "expires_at"
] });
export const x_1503283_vrm_approval = Table({ name: "x_1503283_vrm_approval", label: "Vendor Approval", display: "number", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false, autoNumber: {
  "prefix": "VRP",
  "number": 1000,
  "numberOfDigits": 7
},  schema: { number: StringColumn({
  "label": "Number",
  "maxLength": 160,
  "readOnly": true,
  "default": "javascript:global.getNextObjNumberPadded();"
}),
vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
assessment: ReferenceColumn({
  "label": "Assessment",
  "referenceTable": "x_1503283_vrm_assessment"
}),
requested_by: ReferenceColumn({
  "label": "Requested by",
  "referenceTable": "sys_user"
}),
approver: ReferenceColumn({
  "label": "Approver",
  "referenceTable": "sys_user"
}),
state: StringColumn({
  "label": "Approval state",
  "maxLength": 160,
  "choices": {
    "requested": "Requested",
    "approved": "Approved",
    "rejected": "Rejected",
    "invalidated": "Invalidated"
  },
  "dropdown": "dropdown_with_none",
  "default": "requested"
}),
decision_notes: StringColumn({
  "label": "Decision notes",
  "maxLength": 4000
}),
decided_by: ReferenceColumn({
  "label": "Decided by",
  "referenceTable": "sys_user"
}) } });

Acl({ $id: Now.ID["approval_read"], type: 'record', table: "x_1503283_vrm_approval", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["approval_report"], type: 'record', table: "x_1503283_vrm_approval", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["approval_write"], type: 'record', table: "x_1503283_vrm_approval", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_create"], type: 'record', table: "x_1503283_vrm_approval", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_delete"], type: 'record', table: "x_1503283_vrm_approval", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["approval_number_write"], type: 'record', table: "x_1503283_vrm_approval", field: "number", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_vendor_write"], type: 'record', table: "x_1503283_vrm_approval", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_assessment_write"], type: 'record', table: "x_1503283_vrm_approval", field: "assessment", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_requested_by_write"], type: 'record', table: "x_1503283_vrm_approval", field: "requested_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_approver_write"], type: 'record', table: "x_1503283_vrm_approval", field: "approver", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_state_write"], type: 'record', table: "x_1503283_vrm_approval", field: "state", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_decision_notes_write"], type: 'record', table: "x_1503283_vrm_approval", field: "decision_notes", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["approval_decided_by_write"], type: 'record', table: "x_1503283_vrm_approval", field: "decided_by", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["approval_guard"], name: "VRM protect approval", table: "x_1503283_vrm_approval", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_approval", view: default_view, sections: [{ caption: "Vendor Approval", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "number"
  },
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "assessment"
  },
  {
    "type": "table_field",
    "field": "requested_by"
  },
  {
    "type": "table_field",
    "field": "approver"
  },
  {
    "type": "table_field",
    "field": "state"
  },
  {
    "type": "table_field",
    "field": "decision_notes"
  },
  {
    "type": "table_field",
    "field": "decided_by"
  }
] }] }] });

List({ table: "x_1503283_vrm_approval", view: default_view, columns: [
  "number",
  "vendor",
  "assessment",
  "requested_by",
  "approver",
  "state",
  "decision_notes"
] });
export const x_1503283_vrm_activity = Table({ name: "x_1503283_vrm_activity", label: "Vendor Risk Activity", display: "action", audit: true, allowWebServiceAccess: true, accessibleFrom: 'public', actions: { read: true, create: false, update: false, delete: false }, allowConfiguration: false, allowNewFields: false, createAccessControls: false,   schema: { vendor: ReferenceColumn({
  "label": "Vendor",
  "referenceTable": "x_1503283_vrm_vendor",
  "mandatory": true
}),
assessment: ReferenceColumn({
  "label": "Assessment",
  "referenceTable": "x_1503283_vrm_assessment"
}),
action: StringColumn({
  "label": "Action",
  "maxLength": 160
}),
details: StringColumn({
  "label": "Details",
  "maxLength": 4000
}),
actor: ReferenceColumn({
  "label": "Actor",
  "referenceTable": "sys_user"
}),
occurred_at: DateTimeColumn({
  "label": "Occurred at"
}),
flow_processed: BooleanColumn({
  "label": "Flow processed",
  "default": false
}) } });

Acl({ $id: Now.ID["activity_read"], type: 'record', table: "x_1503283_vrm_activity", operation: 'read', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["activity_report"], type: 'record', table: "x_1503283_vrm_activity", operation: 'report_on', roles: [role_user], adminOverrides: true, script: "answer = new VrmService().canReadRecord(current);" });

Acl({ $id: Now.ID["activity_write"], type: 'record', table: "x_1503283_vrm_activity", operation: 'write', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_create"], type: 'record', table: "x_1503283_vrm_activity", operation: 'create', roles: [role_user], adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_delete"], type: 'record', table: "x_1503283_vrm_activity", operation: 'delete', adminOverrides: false, script: 'answer = false;' });

Acl({ $id: Now.ID["activity_vendor_write"], type: 'record', table: "x_1503283_vrm_activity", field: "vendor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_assessment_write"], type: 'record', table: "x_1503283_vrm_activity", field: "assessment", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_action_write"], type: 'record', table: "x_1503283_vrm_activity", field: "action", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_details_write"], type: 'record', table: "x_1503283_vrm_activity", field: "details", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_actor_write"], type: 'record', table: "x_1503283_vrm_activity", field: "actor", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_occurred_at_write"], type: 'record', table: "x_1503283_vrm_activity", field: "occurred_at", operation: 'write', adminOverrides: false, script: "answer = false;" });

Acl({ $id: Now.ID["activity_flow_processed_write"], type: 'record', table: "x_1503283_vrm_activity", field: "flow_processed", operation: 'write', adminOverrides: false, script: "answer = false;" });

BusinessRule({ $id: Now.ID["activity_guard"], name: "VRM protect activity", table: "x_1503283_vrm_activity", when: 'before', action: ['insert', 'update', 'delete'], active: true, order: 10, script: "(function(current, previous) { try { new VrmService().protect(current, previous); } catch (e) { gs.addErrorMessage(String(e.message || e)); current.setAbortAction(true); } })(current, previous);" });

Form({ table: "x_1503283_vrm_activity", view: default_view, sections: [{ caption: "Vendor Risk Activity", content: [{ layout: 'one-column', elements: [
  {
    "type": "table_field",
    "field": "vendor"
  },
  {
    "type": "table_field",
    "field": "assessment"
  },
  {
    "type": "table_field",
    "field": "action"
  },
  {
    "type": "table_field",
    "field": "details"
  },
  {
    "type": "table_field",
    "field": "actor"
  },
  {
    "type": "table_field",
    "field": "occurred_at"
  }
] }] }] });

List({ table: "x_1503283_vrm_activity", view: default_view, columns: [
  "vendor",
  "assessment",
  "action",
  "details",
  "actor",
  "occurred_at"
] });
ScriptInclude({ $id: Now.ID["policy"], name: 'VrmPolicy', active: true, clientCallable: false, accessibleFrom: 'package_private', script: Now.include('../server/VrmPolicy.js') });

ScriptInclude({ $id: Now.ID["service"], name: 'VrmService', active: true, clientCallable: false, accessibleFrom: 'package_private', script: Now.include('../server/VrmService.js') });

BusinessRule({ $id: Now.ID["response_condition_refresh"], name: 'VRM refresh conditional questions', table: 'x_1503283_vrm_response', when: 'after', action: ['update'], active: true, condition: "current.answer.changes()", order: 100, script: "new VrmService().refreshConditions(current.getValue('assessment'));" });

ClientScript({ $id: Now.ID["response_choices"], name: 'VRM contextual answer options', table: 'x_1503283_vrm_response', type: 'onLoad', active: true, uiType: 'all', script: "function onLoad() { var existing = g_form.getValue('answer'); var options; try { options = JSON.parse(g_form.getValue('options_json')); } catch(e) { return; } g_form.clearOptions('answer'); g_form.addOption('answer', '', '-- Select an answer --'); Object.keys(options).forEach(function(key) { g_form.addOption('answer', key, key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g, ' ')); }); if (g_form.getValue('allow_na') === 'true') g_form.addOption('answer', 'na', 'Not applicable'); g_form.setValue('answer', existing); g_form.setDisplay('options_json', false); g_form.setDisplay('allow_na', false); var active = g_form.getValue('applicable') === 'true'; if (!active) { g_form.setReadOnly('answer', true); g_form.addInfoMessage('This question is currently excluded by the questionnaire conditions.'); } if (g_form.getValue('evidence_required') === 'true' && active) g_form.addInfoMessage('Attach supporting evidence using the paperclip before submitting the assessment.'); }" });

export const mainMenu = ApplicationMenu({ $id: Now.ID["main_menu"], title: 'Vendor Risk Management', active: true, roles: [role_user], order: 100 });
UiPage({ $id: Now.ID["overview_page"], endpoint: 'x_1503283_vrm_overview.do', category: 'general', html: Now.include('../server/overview.html') });

Acl({ $id: Now.ID["overview_access"], type: 'ui_page', name: 'x_1503283_vrm_overview', operation: 'read', roles: [role_app_admin], adminOverrides: true });

Record({ $id: Now.ID["module_overview"], table: 'sys_app_module', data: { title: 'Overview', application: mainMenu, active: true, order: 10, link_type: 'DIRECT', query: 'x_1503283_vrm_overview.do', roles: [role_app_admin] } });
Record({ $id: Now.ID["module_vendor"], table: 'sys_app_module', data: { title: "Vendors", application: mainMenu, active: true, order: 100, link_type: 'LIST', name: "x_1503283_vrm_vendor", roles: [role_user] } });
Record({ $id: Now.ID["module_questionnaire"], table: 'sys_app_module', data: { title: "Questionnaire Versions", application: mainMenu, active: true, order: 200, link_type: 'LIST', name: "x_1503283_vrm_questionnaire", roles: [role_user] } });
Record({ $id: Now.ID["module_assessment"], table: 'sys_app_module', data: { title: "Vendor Assessments", application: mainMenu, active: true, order: 300, link_type: 'LIST', name: "x_1503283_vrm_assessment", roles: [role_user] } });
Record({ $id: Now.ID["module_response"], table: 'sys_app_module', data: { title: "Assessment Responses", application: mainMenu, active: true, order: 400, link_type: 'LIST', name: "x_1503283_vrm_response", roles: [role_user] } });
Record({ $id: Now.ID["module_finding"], table: 'sys_app_module', data: { title: "Risk Findings", application: mainMenu, active: true, order: 500, link_type: 'LIST', name: "x_1503283_vrm_finding", roles: [role_user] } });
Record({ $id: Now.ID["module_remediation"], table: 'sys_app_module', data: { title: "Remediation Tasks", application: mainMenu, active: true, order: 600, link_type: 'LIST', name: "x_1503283_vrm_remediation", roles: [role_user] } });
Record({ $id: Now.ID["module_exception"], table: 'sys_app_module', data: { title: "Risk Exceptions", application: mainMenu, active: true, order: 700, link_type: 'LIST', name: "x_1503283_vrm_exception", roles: [role_user] } });
Record({ $id: Now.ID["module_approval"], table: 'sys_app_module', data: { title: "Vendor Approvals", application: mainMenu, active: true, order: 800, link_type: 'LIST', name: "x_1503283_vrm_approval", roles: [role_user] } });
Record({ $id: Now.ID["module_activity"], table: 'sys_app_module', data: { title: "Vendor Risk Activity", application: mainMenu, active: true, order: 900, link_type: 'LIST', name: "x_1503283_vrm_activity", roles: [role_user] } });
UiAction({ $id: Now.ID["issue_assessment"], name: "Issue Assessment", table: 'x_1503283_vrm_vendor', active: true, actionName: "issue_assessment", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_assessor,role_app_admin], condition: "current.lifecycle != 'assessing'", script: "try { var result = new VrmService().issue(current.getUniqueValue(), (function() { var q = new GlideRecord('x_1503283_vrm_questionnaire'); q.addQuery('state','published'); q.orderByDesc('version'); q.query(); if (!q.next()) throw new Error('Publish a questionnaire first'); return q.getUniqueValue(); })(), 'manual:' + current.getValue('sys_mod_count')); gs.addInfoMessage('Issue Assessment completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["submit_assessment"], name: "Submit and Score", table: 'x_1503283_vrm_assessment', active: true, actionName: "submit_assessment", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_assessor,role_app_admin], condition: "current.state == 'issued'", script: "try { var result = new VrmService().submit(current.getUniqueValue()); gs.addInfoMessage('Submit and Score completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["request_approval"], name: "Request Approval", table: 'x_1503283_vrm_vendor', active: true, actionName: "request_approval", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_assessor,role_app_admin], condition: "current.latest_assessment != '' && current.lifecycle != 'approved' && current.lifecycle != 'pending_approval'", script: "try { var result = new VrmService().requestApproval(current.getUniqueValue()); gs.addInfoMessage('Request Approval completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["verify_remediation"], name: "Verify Remediation", table: 'x_1503283_vrm_remediation', active: true, actionName: "verify_remediation", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_assessor,role_app_admin], condition: "current.state == 'resolved'", script: "try { var result = new VrmService().verify(current.getUniqueValue()); gs.addInfoMessage('Verify Remediation completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["request_exception"], name: "Request Exception", table: 'x_1503283_vrm_finding', active: true, actionName: "request_exception", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_assessor,role_remediation_owner,role_app_admin], condition: "current.critical == false && current.state == 'open'", script: "try { var result = new VrmService().exception(current.getUniqueValue(), current.getValue('exception_reason'), current.getValue('exception_until')); gs.addInfoMessage('Request Exception completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["approve_vendor"], name: "Approve Vendor", table: 'x_1503283_vrm_approval', active: true, actionName: "approve_vendor", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_approver], condition: "current.state == 'requested' && current.approver == gs.getUserID()", script: "try { var result = new VrmService().decideApproval(current.getUniqueValue(), 'approved', 'Approved through form action'); gs.addInfoMessage('Approve Vendor completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["reject_vendor"], name: "Reject Vendor", table: 'x_1503283_vrm_approval', active: true, actionName: "reject_vendor", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_approver], condition: "current.state == 'requested' && current.approver == gs.getUserID()", script: "try { var result = new VrmService().decideApproval(current.getUniqueValue(), 'rejected', 'Rejected by assigned approver'); gs.addInfoMessage('Reject Vendor completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["approve_exception"], name: "Approve Exception", table: 'x_1503283_vrm_exception', active: true, actionName: "approve_exception", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_approver], condition: "current.state == 'requested' && current.approver == gs.getUserID()", script: "try { var result = new VrmService().decideException(current.getUniqueValue(), 'approved'); gs.addInfoMessage('Approve Exception completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

UiAction({ $id: Now.ID["reject_exception"], name: "Reject Exception", table: 'x_1503283_vrm_exception', active: true, actionName: "reject_exception", showInsert: false, showUpdate: true, form: { showButton: true }, roles: [role_approver], condition: "current.state == 'requested' && current.approver == gs.getUserID()", script: "try { var result = new VrmService().decideException(current.getUniqueValue(), 'rejected'); gs.addInfoMessage('Reject Exception completed'); action.setRedirectURL(current); } catch(e) { gs.addErrorMessage(String(e.message || e)); action.setRedirectURL(current); }" });

RestApi({ $id: Now.ID["workflow_api"], name: 'Vendor Risk Workflow', serviceId: 'vendor_risk', active: true, consumes: 'application/json', produces: 'application/json', routes: [{ $id: Now.ID["workflow_action"], name: 'Execute workflow action', method: 'POST', path: '/actions/{action}', authentication: true, authorization: false, script: Now.include('../server/rest-router.js') }] });

ScheduledScript({ $id: Now.ID["daily_maintenance"], name: 'VRM daily reminders and reassessment', active: true, frequency: 'daily', executionTime: { hours: 4, minutes: 0, seconds: 0 }, timeZone: 'UTC', script: "new VrmService().maintenance();" });

Record({ $id: Now.ID["event_assessment_assigned"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.assessment_assigned", table: "x_1503283_vrm_assessment", description: "Assessment assigned", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_assessment_assigned"], name: "VRM Assessment assigned", table: 'x_1503283_vrm_assessment', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.assessment_assigned' }, recipientDetails: { recipientFields: ['assessor'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Assessment assigned: ${number}", messageText: "Assessment assigned. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["event_remediation_assigned"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.remediation_assigned", table: "x_1503283_vrm_remediation", description: "Remediation assigned", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_remediation_assigned"], name: "VRM Remediation assigned", table: 'x_1503283_vrm_remediation', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.remediation_assigned' }, recipientDetails: { recipientFields: ['assigned_to'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Remediation assigned: ${number}", messageText: "Remediation assigned. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["event_remediation_overdue"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.remediation_overdue", table: "x_1503283_vrm_remediation", description: "Remediation overdue", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_remediation_overdue"], name: "VRM Remediation overdue", table: 'x_1503283_vrm_remediation', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.remediation_overdue' }, recipientDetails: { recipientFields: ['assigned_to'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Remediation overdue: ${number}", messageText: "Remediation overdue. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["event_approval_requested"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.approval_requested", table: "x_1503283_vrm_approval", description: "Vendor approval requested", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_approval_requested"], name: "VRM Vendor approval requested", table: 'x_1503283_vrm_approval', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.approval_requested' }, recipientDetails: { recipientFields: ['approver'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Vendor approval requested: ${number}", messageText: "Vendor approval requested. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["event_exception_requested"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.exception_requested", table: "x_1503283_vrm_exception", description: "Risk exception requested", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_exception_requested"], name: "VRM Risk exception requested", table: 'x_1503283_vrm_exception', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.exception_requested' }, recipientDetails: { recipientFields: ['approver'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Risk exception requested: ${number}", messageText: "Risk exception requested. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["event_vendor_decision"], table: 'sysevent_register', data: { event_name: "x_1503283_vrm.vendor_decision", table: "x_1503283_vrm_vendor", description: "Vendor decision recorded", fired_by: 'VrmService' } });
EmailNotification({ $id: Now.ID["notification_vendor_decision"], name: "VRM Vendor decision recorded", table: 'x_1503283_vrm_vendor', active: true, triggerConditions: { generationType: 'event', eventName: 'x_1503283_vrm.vendor_decision' }, recipientDetails: { recipientFields: ['requested_by'], sendToCreator: true }, emailContent: { contentType: 'text/plain', subject: "Vendor decision recorded: ${number}", messageText: "Vendor decision recorded. Review the record in Vendor Risk Management. ${URI_REF}", includeAttachments: false } });

Record({ $id: Now.ID["validity_days"], table: 'sys_properties', data: { name: 'x_1503283_vrm.validity_days', value: '365', type: 'integer', description: 'Assessment validity in days', is_private: true } });
Record({ $id: Now.ID["seed_questionnaire"], table: 'x_1503283_vrm_questionnaire', data: { name: 'Vendor Security Assessment v1', code: "vendor_security", version: 1, state: 'published', definition_json: "{\"code\":\"vendor_security\",\"version\":1,\"failThreshold\":60,\"questions\":[{\"id\":\"sensitive_data\",\"text\":\"Will this vendor process sensitive business data?\",\"weight\":1,\"critical\":false,\"allowNA\":false,\"evidenceRequired\":false,\"options\":{\"yes\":20,\"no\":0},\"createsFinding\":false},{\"id\":\"encryption\",\"text\":\"Is sensitive data encrypted in transit and at rest?\",\"weight\":5,\"critical\":true,\"allowNA\":false,\"evidenceRequired\":true,\"options\":{\"yes\":0,\"partial\":50,\"no\":100},\"condition\":{\"questionId\":\"sensitive_data\",\"values\":[\"yes\"]}},{\"id\":\"access_review\",\"text\":\"How frequently are privileged access rights reviewed?\",\"weight\":3,\"critical\":false,\"allowNA\":false,\"evidenceRequired\":true,\"options\":{\"quarterly\":0,\"annually\":40,\"never\":100}},{\"id\":\"recovery_test\",\"text\":\"Has the vendor tested its recovery plan within the last year?\",\"weight\":3,\"critical\":false,\"allowNA\":false,\"evidenceRequired\":true,\"options\":{\"yes\":0,\"partial\":40,\"no\":100}},{\"id\":\"subprocessors\",\"text\":\"Does the vendor use subprocessors for this service?\",\"weight\":1,\"critical\":false,\"allowNA\":false,\"evidenceRequired\":false,\"options\":{\"yes\":20,\"no\":0},\"createsFinding\":false},{\"id\":\"subprocessor_review\",\"text\":\"Are all subprocessors assessed before use?\",\"weight\":2,\"critical\":false,\"allowNA\":false,\"evidenceRequired\":true,\"options\":{\"yes\":0,\"partial\":50,\"no\":100},\"condition\":{\"questionId\":\"subprocessors\",\"values\":[\"yes\"]}}]}" } });
Record({ $id: Now.ID["report_risk_distribution"], table: 'sys_report', data: { title: "Vendor risk distribution", table: 'x_1503283_vrm_vendor', type: 'pie', aggregate: 'COUNT', field: 'risk_band', roles: [role_app_admin] } });
Record({ $id: Now.ID["report_vendor_lifecycle"], table: 'sys_report', data: { title: "Vendor onboarding lifecycle", table: 'x_1503283_vrm_vendor', type: 'bar', aggregate: 'COUNT', field: 'lifecycle', roles: [role_app_admin] } });
Record({ $id: Now.ID["report_findings"], table: 'sys_report', data: { title: "Risk findings by criticality", table: 'x_1503283_vrm_finding', type: 'bar', aggregate: 'COUNT', field: 'critical', roles: [role_app_admin] } });
Record({ $id: Now.ID["report_remediation"], table: 'sys_report', data: { title: "Remediation progress", table: 'x_1503283_vrm_remediation', type: 'bar', aggregate: 'COUNT', field: 'state', roles: [role_app_admin] } });
